# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param Y outcome vector
#' @param X predictors matrix
#' @return Regression results
LR_cpp <- function(Y, X) {
    .Call(`_LR_LR_cpp`, Y, X)
}

